const easyQuestions = [
    {
        question: 'A computer that is part of a bot-net is typically called?',
        options: ["Zombie", "Undead", "Vampire", "Spider"],
        answer: "Zombie",
        explanation: "In the context of a botnet, a computer that has been compromised and controlled by a hacker or a malicious entity without the knowledge of its owner is often referred to as a <i>zombie</i>. This term is used because, much like the fictional undead creature, a zombie computer is essentially <i>enslaved</i> and manipulated by an external force (the botnet operator) to carry out tasks, such as launching coordinated cyber attacks, sending spam, or performing other malicious activities, all without the user&#39s consent or awareness. Just as a zombie is controlled by an external entity in popular culture, a compromised computer in a botnet surrenders its autonomy to the botnet operator.",
        multiplier: "1",
    },
    {
        question: 'What term is commonly used to describe a type of software specifically designed to disrupt, damage, or gain unauthorized access to computer systems through self-replicating?',
        options: ["Bug", "Virus", "Glitch", "Worm"],
        answer: "Virus",
        explanation: "A computer virus is a type of malicious software that replicates itself and spreads to other programs, files, or systems. It is designed to cause harm, such as corrupting data, stealing information, or disrupting normal computer operations.",
        multiplier: "1",
    },
    {
        question: 'What kind of malware prevents the victim from accessing their data until the ransom is paid?',  
        options: ["Worms", "Trojans", "Ransomware", "Keyloggers"],
        answer: "Ransomware",
        explanation: "Ransomware is malicious software that encrypts a victim&#39s files, making them inaccessible. The attackers then demand a ransom, in exchange for a decryption key to restore access to the files.",
        multiplier: "1",
    },
    {
        question: 'What does this sentence describe? Intimidating conduct enabled via digital methods, such as sending text messages',
        options: ["Cyberbullying", "Phishing", "Worm", "Harassment"],
        answer: "Cyberbullying",
        explanation: "Cyberbullying involves the intentional and repeated use of technology to harass, intimidate, or harm others, and texting is one of the common mediums through which such harmful behavior takes place.",
        multiplier: "1",
    },
    {
        question: 'This malware monitors and records users keystrokes(e.g password entry) and sends them to a remote source ',
        options: ["virus", "ransomware", "keyloggers", "worm"],
        answer: "keyloggers",
        explanation: "A keylogger is a a type of spyware that  monitors and records a person&#39s keystrokes as they type on their device.",
        multiplier: "1",
    },    
    {
        question: 'What kind of virus disguises itself with in a desirable program for malicious intention?',
        options: ["Rootkit", "Adware", "Ransomware", "Trojan"],
        answer: "Trojan",
        explanation: "A trojan is a virus that will disguise itself as a legitimate program. Their goal is to trick victims into clicking, installing, and opening, which will allow them to export, modify or delete the content of the victim's computer.",
        multiplier: "1"
    },
    {
        question: 'A worm collects user data and utilizes it to present personalized unwanted advertisements to the user.',
        options: ["True", "False", "Partially True", "Partially False"],
        answer: "False",
        explanation: "Adware is the correct term. This type of malware displays unwanted advertisements to the user. They can take various forms such as pop-up ads and banners.",
        multiplier: "1",
    },
    {
        question: 'What is the act of transforming plain text into an incomprehensible format through a scrambling process?',
        options: ["Hacking", "Encryption", "Pharming", "Decryption"],
        answer: "Encryption",
        explanation: "Encryption is a security technique that involves encoding information in such a way that only authorized parties can access and understand it. The <i>scrambling process</i> aligns with the fundamental concept of encryption, where algorithms are used to convert plaintext into ciphertext, making the original information unreadable without the appropriate decryption key",
        multiplier: "1",
    },
    {
        question: 'True or False: A botnet is when one computer is infected by a type of malware and under the control of a hacker?',
        options: ["True", "False", "Partially True", "Partially False"],
        answer: "False",
        explanation: "A botnet is when a multiple or a group of computers are infected by a malware controlled by a hacker.",
        multiplier: "1",
    },
    {
        question: 'Which of the following attacks is usually perpetrated by an insider of an organization',
        options: ["Logic Bomb", "Spyware", "Ransomware", "Spyware"],
        answer: "Logic Bomb",
        explanation: "A logic bomb is a set of instructions in a program that carries a malicious payload and lies dormant but only goes off only after certain conditions are met",
        multiplier: "1",
    },
    {
        question: 'Malware encompasses malicious computer programs, including viruses, worms, and trojans, employed by hackers to infiltrate your computer and inflict damage.',
        options: ["True", "False", "Partially True", "Partially False"],
        answer: "True",
        explanation: "This statement is accurate because malware, short for malicious software, indeed consists of harmful computer programs created with nefarious intent and viruses, worms and trojans are different types of malware, each designed to compromise the security of a computer system.",
        multiplier: "1",
    },
    {
        question: 'When should we perform a virus scan?',
        options: ["When you add/download files to a computer", "When you execute code", "When your computer is turned off", "Only A and B"],
        answer: "Only A and B",
        explanation: "Performing a virus scan is recommended when you add or download files to a computer (option A) because this is a common point of entry for malware. In addition, executing code (option B) is another potential vulnerability that may expose a system to security risks, therefore running a virus scan is also highly recommended.",
        multiplier: "1",
    },
    {
        question: 'Spyware is more dangerous than rootkit',
        options: ["True", "False", "Partially True", "Partially False"],
        answer: "False",
        explanation: "Rootkits are more dangerous than spyware as spyware primarily focuses on data collection and privacy invasion, while rootkits have more capabilities and have a higher level of system access and control they can grant to attackers. One being system manipulation, this can include altering system files, disabling security features and providing backdoor access for other types of malware.",
        multiplier: "1",
    },
    {
        question: 'A malicious software that collects information about users knowledge or consent is called?',
        options: ["Dropper", "Worm", "Trojan", "Spyware"],
        answer: "Spyware",
        explanation: "A spyware is a type of malware that infects users devices, gathers data and sends it to third parties without their consent or knowledge",
        multiplier: "1",
    },
    {
        question: 'What is the name of the type of malware that uses fear and intimidation to manipulate users into taking specific actions?',
        options: ["Scareware", "Spyware", "Trojan", "Worm"],
        answer: "Scareware",
        explanation: "This type of malware usually displays alarming messages or false information on a user&#39s computer screen, falsely claiming that the system is infected with malware or that legal action will be taken unless immediate steps are followed. The intention behind it is to prompt the user to purchase fake or unnecessary security software, pay a ransom or divulge personal information.",
        multiplier: "1",
    },
    {
        question: 'Is <i>dropper</i> a type of trojan or a type of phishing?',
        options: ["Phishing", "Trojan", "All of the above", "None of the Above"],
        answer: "Trojan",
        explanation: "Dropper is a type of trojan, it refers to a malicious software or program that is designed to install and execute additional malware components onto a victim&#39s computer, these malware components can be updated and redownloaded. The term <i>dropper</i> comes from its primary function, which is to <i>drop</i> or deposit these additional malicious payloads onto the targeted system. Even if the malware is removed, dropper can install it again",
        multiplier: "1",
    },
    {
        question: 'Once installed , what collection of software tools can be used to gain remote control and access to a computer system?',
        options: ["Penetration Test", "Logic bomb", "Rootkit", "Worm"],
        answer: "Rootkit",
        explanation: "A rootkit is a malicious program that provides  continuous root-level privileges( i.e administrative) to a device while concealing its presence. Once installed, attackers can use it to create backdoors in the installed device and introduce other types of malware for further attacks  ",
        multiplier: "1",
    },    
    {
        question: 'A worm is capable of spreading without any user interaction.',
        options: ["True", "False", "Partially True", "Partially False"],
        answer: "True",
        explanation: "This is true! A worm is self-replicating and doesn&#39t require user interaction to spread as it can independently exploit vulnerabilities in a computer (or network) and replicate itself to other systems without any interaction with the user.",
        multiplier: "1",
    },   
];

const mediumQuestions = [
    {
        question: "Which malmare is more dangerous: Virus or Worm?",
        options: ["Worm", "Virus"],
        answer: "Worm",
        explanation: "Worm is the more dangerous malware because its can spread faster, with little to no user involvement.",
        multiplier: "2",
        },
        {
        question: "Fill in the blanks: A virus that can  _____  its own code to avoid detection yet retain the same basic routine after each infection is called a polymorphic virus.",
        options: ["self-modify", "create", "delete", "run"],
        answer: "self-modify",
        explanation: "A polymorphic virus is created to self modify its own code while keeping the original algorithm to avoid any detection ",
        multiplier: "2",
        },
        {
        question: "What was the first PC virus?",
        options: ["Creeper", "Brain", "Michelangelo", "Code Red"],
        answer: "Brain",
        explanation: "The first PC virus, <i>Brain</i> was created in 1986 by 2 pakistani brothers, Basit and Amjad Farroq Alvi. They developed this virus to protect their commercial software from piracy. Brain worked by infecting the boot sector of floppy disks, spreading when users inserted infected disks into their computers. ",
        multiplier: "2",
        },
        {
        question: "Malware typically does one or more of: ",
        options: ["Steal Data", "Display Advertising", "Steal CPU Cycles", "All of the Above"],
        answer: "All of the Above",
        explanation: "Malware can engage in a variety of malicious activities, including stealing data, displaying advertising and stealing CPU cycles, depending on the specific type and purpose of the malware. ",
        multiplier:"2",
        },
        {
        question: "Which of the below is NOT a social engineering attack?",
        options: ["Phishing", "Scareware", "Baiting", "Pretexting"],
        answer: "Scareware",
        explanation: "Scareware is NOT a social engineering attack because it does not involve the use of psychological manipulation of people using their personal confidential information",
        multiplier: "2",
        },
        {
        question: "What is the name of the first internet worm?",
        options: ["Creeper", "Code Red", "Morris Worm", "None of the above"],
        answer: "Morris Worm",
        explanation: "Morris worm was the first internet worm. It was named after its creator Robert Tappan Morris. It was launched from MIT on November 2,1988.A bug in the worm caused it to re-infect computers over and over , resulting in a denial of service attack. It gained substantial attention from the mainstream media which led to the first-ever conviction under the 1986 Computer Fraud and Abuse Act in the United States.",
        multiplier: "2",
        },
        {
        question: "What is a false negative error in virus scanning?",
        options: ["When an innocent program is declared a virus", "When a virus is declared innocent", "A and B", "Neither A or B"],
        answer: "When a virus is declared innocent",
        explanation: "A false negative error in virus scanning occurs when a virus or malicious software is present on a system, but the antivirus software fails to detect it and incorrectly declares the file or program as safe or innocent.",
        multiplier: "2",
        },
        {
        question: "What was the Stuxnet malware designed to do? ",
        options: ["Steal personal information", "Display unwanted ads on user's systems", "Sabotage Iran's Nuclear program", "Encrypt files and demand ransom for decryption keys"],
        answer: "Sabotage Iran's Nuclear program",
        explanation: "The Stuxnet was a malicious computer worm engineered with a specific intent of disrupting Iran's nuclear program by inflicting damage on the centrifuges used for uranium enrichment. It was created by the US and Israel's intelligence agencies  ",
        multiplier: "2",
        },
        {
        question: "After installation, what is the commonly used term for the set of software tools employed to achieve remote access and control over a computer or system?",
        options: ["Firewall", "Rootkit", "Logic bomb", "Encryption software"],
        answer: "Rootkit",
        explanation: "It is a type of malicious software that once installed on a computer, provides unauthorized users with hidden access to the system. It is often used for illegal activities such spying, data theft, etc.r",
        multiplier: "2",
        },
        {
        question: "_________ is a controversial tool designed to spread through networks with the purpose of distributing security patches and updates for known vulnerabilities.",
        options: ["Ethical Worm", "Patch Management", "Spyware", "None of the above"],
        answer: "Ethical Worm",
        explanation: "An ethical worm operates similarly to traditional worms but is designed for positive purposes, aiming to fix or patch system vulnerabilities rather than exploit them.",
        multiplier: "2",
        },
        {
        question: "What creates an infected file?",
        options: [ "A virus modifies and copies its own code onto any type of file", "A virus deletes an existing file", "A virus modifies and copies its own code onto an existing executable file", "none of the above"],
        answer: "A virus modifies and copies its own code onto an existing executable file",
        explanation: "In order for a file to be infected by a virus, it must first be an executable, existing file for the virus to modify and copy its own code",
        multiplier: "2",
        },
        {
        question: "'Cryptojacking is a trend that involves cyber criminals hijacking third-party home or work computers to <i>mine</i> for cryptocurrency' Is this True or False?",
        options: ["True", "False", "Partially True", "Partially False"],
        answer: "True",
        explanation: "Cryptojacking refers to the unauthorized use of an individual's computer for cryptocurrency mining. Typically, this involves the installation of malicious software on the target's computer, which covertly employs their processing power to mine for cryptocurrency without their knowledge or consent.",
        multiplier: "2",
        },
        {
        question: "Which of the following statements is true of both Computer worms and virus",
        options: ["They cannot be detected by an anti-malware software", "They are self-replicating", "They infect files systems with malicious code", "All of the Above"],
        answer: "They are self-replicating",
        explanation: "Both the Computer worm and virus have the ability to self replicate themselves (create copies of themselves). However, their methods of propagation are different. A virus requires a host file to spread and needs human interaction to activate it, while a worm can spread autonomously without needing to attach itself to a host file or program  ",
        multiplier: "2",
        },
        {
        question: "What is not true of a logic bomb?",
        options: ["Usually orchestrated by an insider in the organization", "It is similar to trojan", "It is similar to a worm", "It is triggered when some condition is met" ],
        answer: "It is similar to a worm",
        explanation: "They are distinct types of malware with different characteristics. Logic bombs are triggered by specific conditions, whereas worms propagate autonomously without such triggers.",
        multiplier: "2",
        },
        {
        question: "Stuxnet is a worm, a virus and a rootkit. True or False?",
        options: ["True", "False", "Partially True", "Partially False"],
        answer: "True",
        explanation: "Many instances of malware fit into multiple categories as when categorizing malware it involves considering its multiple functionalities and capabilities. Stuxnet is a worm because it has the ability to self-replicate and spread across networks. It is also a virus as it can infect and modify other programs on a host system. Lastly it is also a rootkit because it employs techniques to conceal its presence on infected systems.",
        multiplier: "2",
        },
        {
        question: "When scanning for a virus, is a false negative or a false positive worse?",
        options: ["false positive ", "false negative"],
        answer: "false negative",
        explanation: "false negative is when a virus is declared innocent, while a false positive is when an innocent program is declared a virus. When a virus is declared innocent, it negatively affects confidentiality, integrity and availability, as well as allow the virus to continue going undetected. While a false positive only negatively affects availability.",
        multiplier: "2",
        },
        {
        question: "Fill in the blank. Phishing, spear phishing and vishing are all types of ________",
        options: ["Social Engineering", "Malware", "Firewall Attacks", "None of the above"],
        answer: "Social Engineering",
        Explanation: "Social Engineering: these techniques share one common characteristic - exploiting hum psychology and manipulate individuals into disclosing confidential information or taking actions that compromise security.",
        multiplier: "2",
        },
        
];

const hardQuestions = [
    {
        question: "What term describes the pattern on how a worm spreads? ",
        options: ["Exponential growth", "Logarithmic growth", "Logistic growth", "Linear growth"],
        answer: "Logistic growth",
        explanation: "A worm spreads with a logistic growth as it has a slow initial growth which does not last long then experiences an exponential growth soon after and eventually slows down because there is nothing left to infect.",
        multiplier: "3",
        },
        { 
        question: "Which of the below is the correct order of typical worm progression? ",
        options: ["copies itself to another machine, scans and exploits a security flaw, executes payload immediately", "executes payload after a day, copies itself to another machine, scans and exploits a security flaw", "scans and exploits a security flaw, copies itself to another machine, download payload and condition for execution", "scans and exploits a security flaw, copies itself to another machine, delete a payload"],
        answer: "scans and exploits a security flaw, copies itself to another machine, download payload and condition for execution",
        explanation: "For a typical worm to progress, it must first scan and use a security flaw on a new host, than copies its code onto another machine, and if it were use a payload, it could either: execute it immediately, delay until a certain time or download the payload and condition it for execution, and then repeat step 1",
        multiplier: "3",
        },
        {
        question: "What was the first example of a <i>Warhol Worm</i>?",
        options: ["Sasser", "Stuxnet", "SQL Slammer", "None of these"],
        answer: "SQL Slammer",
        explanation: "A Warhol Worm is a computer worm designed to propagate as rapidly as possible, infecting every susceptible machine across the entire internet within a time frame of 15 minutes or less. SQL Slammer was the first example of a Warhol Worm as it exploited a vulnerability in Microsoft SQL Server and Desktop Engine (MSDE) databases and it started spreading in January 2003. Within a few minutes it infected a large number of systems globally in a rapid, almost instantaneous, widespread distribution. ",
        multiplier: "3",
        },
        {
        question: "What is the main difference between distributed denial of service attacks (DDoS) and denial of service attack (DoS)?",
        options: ["time", "use of keylogging", "size", "use of botnets"],
        answer: "size",
        explanation: "Size is the main difference between DDoS and DoS, because DDoS attacks are at a larger scale than DoS, because DoS uses a single source to flood the target system with traffic to make it inaccessible to the targeted users, while a DDos attack uses multiple devices to generate much more traffic and therefore, DDoS attacks compared to DoS is size. ",
        multiplier: "3",
        },
        {
        question: "Which term refers to a network of compromised intermediary systems that can serve as a launchpad for a DDoS attack?",
        options: ["Intranet", "Ethernet", "Extranet", "Botnet"],
        answer: "Botnet",
        explanation: "A botnet is a number of Internet-connected devices, each of which is running one or more bots. Botnets can be used to perform Distributed Denial-of-Service (DDoS) attacks, steal data, send spam, and allow the attacker access to the device and its connection. The owner can control the botnet using command and control (C&C) software",
        multiplier: "3",
        },
        {
        question: "How does a Trojan usually spread?",
        options: ["Email Attachments", "Fake Software Downloads", "Infected Websites", "All of the Above"],
        answer: "All of the Above",
        explanation: "Trojans can be disguised as legitimate files, documents, softwares, etc. As well, when you visit a compromised website or click a malicious link, it can lead to the download and execution of trojans.",
        multiplier: "3",
        },
        {
        question: "What is the name of the segment of the malware code that is accountable for executing harmful actions is known as:",
        options: ["Firewall", "Virus", "Payload", "Explosion"],
        answer: "Payload",
        explanation: "Payload is the segment of the malware code that encapsulates malicious functions like damaging or compromising the targeted system.", 
        multiplier: "3",
        },
        {
        question: "A collection of zombies is known as a ________",
        options: ["Zombienet", "Botnet", "Infected Network", "None of the Above"],
        answer: "Botnet",
        explanation: "Botnet is the correct term - it is a network of private computers or devices that are infected with malicious software aka zombies. ",
        multiplier: "3",
        },
        {
        question: "What is false about worms?",
        options: ["Worms rely on human interaction", "Worms are self-replicating", "Worms gain unauthorized access to computer systems", "Worms don't need a host program to attach themselves to"],
        answer: "Worms rely on human interaction",
        explanation: "Worms are capable of spreading independently without the need for human interaction. They don't require human action to initiate their propagation - this is why they are particularly effective at rapid distribution.",
        multiplier: "3",
        },
        {
        question: "Which file format is most likely to be associated with the spread of malware?",
        options: [".pdf", ".png", ".exe", "All of the Above"],
        answer: ".exe",
        explanation: "Executable files, marked with the .exe extension, are typically linked to the greatest risk of malware spread due to their ability to run code or commands on a Windows system. They can carry out nearly any action allowed by Windows User Account Control, making them an attractive vehicle for malware attacks.",
        multiplier: "3",
        },
        {
        question: "A malware that changes its code to avoid detection by antivirus signatures is referred to as:",
        options: ["Zero-day exploit", "Botnet", "Polymorphic malware", "Logic bomb"],
        answer: "Polymorphic malware",
        explanation: "Polymorphic malware is aptly named due to its dynamic nature, characterized by the ability to continually change its code to avoid detection by traditional antivirus signatures. This adaptive strategy hinders signature-based detection methods, as the malware generates unique variants with each infection, making it challenging for security systems to keep pace with evolving threats.",
        multiplier: "3",
        },
        {
        question: "What is a common delivery method for drive-by download attacks facilitated by malware?",
        options: ["Email attachments", "Infected USB drives", "Visiting a compromised website", "Social engineering attacks"],
        answer: "Visiting a compromised website",
        explanation: "Visiting a compromised website is a common delivery method for drive-by download attacks as attackers exploit vulnerabilities in web browsers or plugins, automatically downloading and executing malicious content on the user's system without their knowledge. The stealthy nature of these attacks relies on exploiting security weakness silently, making users unaware of the compromise until after the malicious payload has been executed.",
        multiplier: "3",
        },
        {
        question: "A keylogger is a type of malware that records and captures ______.",
        options: ["Mouse movements", "Keystrokes", "Screen captures", "Network traffic"],
        answer: "Keystrokes",
        explanation: "A keylogger is a form of malware that operates covertly, recording and capturing every keystroke made by a user on a computer or mobile device. Its primary purpose is to steal sensitive information, including login credentials and passwords, by logging the user's input. Keyloggers can exist in both hardware and software forms, and their operation constitutes a serious invasion of privacy, often leading to unauthorized access and data theft.",
        multiplier: "3",
        },
        {
        question: "__________ is a technique where malware conceals its true intent from security analysts by behaving innocuously during analysis.",
        options: ["Signature-based detection", "Heuristic analysis", "Zero-day exploit", "Trojan horse defense"],
        answer: "Trojan horse defense",
        explanation: "Trojan horse defense is a tactic employed by malware to deceive security analysts during the analysis phase. The malware conceals its true malicious intent by behaving innocently when subjected to analysis tools and environments. This strategy includes adapting to sandbox environments, delaying the execution of malicious activities, and using polymorphic techniques, making it challenging for analysts to uncover the malware's true nature and intent.",
        multiplier: "3",
        },
        {
        question: "What is considered a drive-by attack?",
        options: ["An attack which involved downloading malicious software without the user's knowledge", "An attack that involves tricking the user into downloading malicious software ", "An attack that involves downloading malicious software from a compromised website", "All of the Above"],
        answer: "All of the Above",
        explanation: "A drive-attack is an attack where the user's device gets infected with a malicious software simply by visiting a compromised website or opening a harmful email attachment. The attack can occur in two ways; either without any user interaction , where the malicious software is downloaded automatically when a compromised webpage is visited  or with user interaction under false pretenses, where the user is tricked into initiating the download",
        multiplier: "3",
        },
        {
        question: "_____ is a malicious code where it disguises itself into a browser like a Trojan horse and has the capability to intercept all actions performed by the browser. ",
        options: ["Man in the middle", "SSL stripping", "Phishing", "Man in the browser"],
        answer: "Man in the browser",
        explanation: "Man in the browser (MitB) is similar to Man in the middle (MitM) where MitM secretly intercepts and forwards messages between two parties that are believed to be communicating with each other in order to steal information at an application level but MitB works on a browser level and disguises itself into it as a Trojan horse",
        multiplier: "3",
        },
        {
        question: "Read the following situation: A former employee embedded a malicious code before his leave from his position at a software company, he programmed the code so that once he left, it would delete all of the companies spreadsheets of important data after three day, what type of maleware did he install?",
        options: ["Trojan Horse", "Rootkit", "Time Bomb", "Logic Bomb"],
        answer: "Time bomb",
        explanation: "Although a logic bomb is similar to a time bomb where they are designed to activate with malicious functions under a specific condition, the situation above is that of a time bomb because the malicious code was set to activate after a predetermined time",
        multiplier: "3",
        },
        {
        question: "Which of the following is NOT true about polymorphic viruses?",
        options: ["They are static viruses that have consistent code structures and typically remain unchanged", "They are able to mutate which it challenging for antivirus softwares to develop fixed patterns to recognize them", "They can replicate themselves with each process having a different code", "Polymorphic viruses can change their appearance to avoid detection by virus detection programs"],
        answer: "They are static viruses that have consistent code structures and typically remain unchanged",
        explanation: "This is incorrect because polymorphic viruses have the ability to change their appearance or code, making each process unique. They are dynamic viruses rather than static in order to avoid detections by anti virus programs and virus scanners",
        multiplier: "3",
        },
];